import type { FormEvent } from "react";
import type { DashboardState, TallyAccount } from "../../lib/types";
import { XIcon } from "../icons";
export type AccountEditor = { mode: "new" | "edit"; account: TallyAccount };
export default function AccountModal({ dashboard, editor, setEditor, onSave }: { dashboard: DashboardState; editor: AccountEditor; setEditor: (value: AccountEditor | null) => void; onSave: (account: TallyAccount, mode: "new" | "edit") => void }) {
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editor.account.name.trim()) return; onSave({ ...editor.account, name: editor.account.name.trim() }, editor.mode); }
  const patch = (changes: Partial<TallyAccount>) => setEditor({ ...editor, account: { ...editor.account, ...changes } });
  return <div className="modal-backdrop" role="presentation"><section className="modal modal-small" role="dialog" aria-modal="true" aria-labelledby="account-editor-title"><form onSubmit={submit}><div className="modal-header"><div><p className="eyebrow">Account</p><h2 id="account-editor-title">{editor.mode === "new" ? "Add account" : "Edit account"}</h2></div><button type="button" className="icon-button icon-button-plain" onClick={() => setEditor(null)} aria-label="Close account editor"><XIcon size={18} /></button></div><div className="modal-body form-stack"><label className="form-field"><span>Account name</span><input required autoFocus value={editor.account.name} onChange={(e) => patch({ name: e.target.value })} placeholder="e.g. TikTok Main" /></label><label className="form-field"><span>Status</span><select value={editor.account.statusId} onChange={(e) => patch({ statusId: e.target.value })}>{dashboard.statuses.map((status) => <option key={status.id} value={status.id}>{status.label}</option>)}</select></label><label className="form-field"><span>Visit link</span><input type="url" value={editor.account.url} onChange={(e) => patch({ url: e.target.value })} placeholder="https://" /></label><div className="field-divider" />{dashboard.fields.map((field) => <label className="form-field" key={field.id}><span>{field.label}</span><div className="number-input-wrap">{field.format === "currency" ? <span>{dashboard.settings.currencySymbol}</span> : null}<input inputMode="decimal" value={editor.account.values[field.id] || ""} onChange={(e) => patch({ values: { ...editor.account.values, [field.id]: e.target.value } })} placeholder="0" /></div></label>)}</div><div className="modal-footer"><button type="button" className="button button-secondary" onClick={() => setEditor(null)}>Cancel</button><button className="button button-primary" type="submit">Save account</button></div></form></section></div>;
}
