import type { CSSProperties } from "react";
import type { DashboardState, TallyAccount } from "../../lib/types";
import { formatValue, safeUrl } from "../../lib/dashboard-utils";
import { DownIcon, ExternalLinkIcon, PencilIcon, TrashIcon, UpIcon } from "../icons";

export default function AccountCard({ dashboard, account, onEdit, onDelete, onMove }: { dashboard: DashboardState; account: TallyAccount; onEdit: () => void; onDelete: () => void; onMove: (direction: -1 | 1) => void }) {
  const status = dashboard.statuses.find((item) => item.id === account.statusId) || dashboard.statuses[0];
  const url = safeUrl(account.url); const index = dashboard.accounts.findIndex((item) => item.id === account.id);
  return <article className="account-card"><div className="account-card-top"><div className="account-title-block"><div className="account-heading-line"><h3>{account.name}</h3><span className="status-pill" style={{ "--status-color": status.color } as CSSProperties}><span className="status-dot" />{status.label}</span></div>{url ? <a className="account-url" href={url} target="_blank" rel="noreferrer">Visit account <ExternalLinkIcon size={15} /></a> : <span className="account-url account-url-muted">No link added</span>}</div><button className="button button-secondary button-compact" onClick={onEdit}><PencilIcon size={15} /> Edit</button></div><dl className="account-values">{dashboard.fields.map((field) => <div className="value-cell" key={field.id}><dt>{field.label}</dt><dd>{formatValue(dashboard, account.values[field.id], field)}</dd></div>)}</dl><div className="card-footer"><div className="order-controls" aria-label={`Reorder ${account.name}`}><button className="icon-button" disabled={dashboard.sortMode !== "manual" || index === 0} onClick={() => onMove(-1)} aria-label={`Move ${account.name} up`}><UpIcon size={16} /></button><button className="icon-button" disabled={dashboard.sortMode !== "manual" || index === dashboard.accounts.length - 1} onClick={() => onMove(1)} aria-label={`Move ${account.name} down`}><DownIcon size={16} /></button><span>{dashboard.sortMode === "manual" ? "Manual order" : "Sorted view"}</span></div><button className="text-button text-danger" onClick={onDelete}><TrashIcon size={15} /> Delete</button></div></article>;
}
